# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    working_directory: ~/counterpoint-v2

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run:
        name: Installing dependencies
        command: |
          set -e
          GCLOUD=${HOME}/google-cloud-sdk/bin/gcloud
          echo ${GCLOUD_SERVICE_KEY} | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json

          if ${GCLOUD} version 2>&1 >> /dev/null; then
              echo "Cloud SDK is already installed"
          else
              SDK_URL=https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-190.0.1-linux-x86_64.tar.gz
              INSTALL_DIR=${HOME}

              cd ${INSTALL_DIR}
              wget ${SDK_URL} -O cloud-sdk.tar.gz
              tar -xzvf cloud-sdk.tar.gz

              ${GCLOUD} components install app-engine-java
          fi

          ${GCLOUD} auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
          ${GCLOUD} config set project ${GOOGLE_PROJECT_ID}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn appengine:deploy
